import { useEffect, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import type { RepositoryClassification } from "../../domain/scoring";
import type { GitHubAudit } from "./run-audit";
import { GitBranchIcon, SearchIcon, ShieldIcon } from "../../components/icons";
import { applyRepositoryView, repositoryViewFromParams, repositoryViewToParams, type RepositoryFilter, type RepositorySort } from "./repository-view";

const classificationOrder: RepositoryFilter[] = ["ALL", "SHOWCASE", "KEEP", "ARCHIVE", "FORK_REVIEW", "REVIEW", "CLEANUP"];
const labels: Record<RepositoryFilter, string> = { ALL: "All", SHOWCASE: "Showcase", KEEP: "Keep", ARCHIVE: "Archive", FORK_REVIEW: "Fork review", REVIEW: "Review", CLEANUP: "Cleanup" };
const styles: Record<RepositoryClassification, string> = { SHOWCASE: "bg-lime-100 text-lime-900 border-lime-300", KEEP: "bg-cobalt-50 text-cobalt-700 border-cobalt-100", ARCHIVE: "bg-slate-100 text-slate-700 border-slate-200", FORK_REVIEW: "bg-violet-50 text-violet-700 border-violet-200", REVIEW: "bg-amber-50 text-amber-800 border-amber-200", CLEANUP: "bg-orange-50 text-orange-800 border-orange-200" };

function Badge({ value }: { value: RepositoryClassification }) { return <span className={`inline-flex whitespace-nowrap rounded-md border px-2 py-1 font-mono text-[10px] font-bold uppercase ${styles[value]}`}>{labels[value]}</span>; }
function date(value?: string) { if (!value) return "Unknown"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "Unknown" : new Intl.DateTimeFormat(undefined, { year: "numeric", month: "short", day: "numeric" }).format(parsed); }

export function AuditDashboard({ audit, onRefresh }: { audit: GitHubAudit; onRefresh: () => void }) {
  const [params, setParams] = useSearchParams();
  const view = repositoryViewFromParams(params);
  const [limit, setLimit] = useState(100);
  useEffect(() => setLimit(100), [view.filter, view.query, view.sort]);
  const visible = useMemo(() => applyRepositoryView(audit.repositories, { filter: view.filter, query: view.query, sort: view.sort }), [audit.repositories, view.filter, view.query, view.sort]);
  const displayed = visible.slice(0, limit);
  const update = (next: Partial<typeof view>) => setParams(repositoryViewToParams({ ...view, ...next }, params), { replace: true });
  const detailUrl = (owner: string, repo: string) => {
    const detailParams = new URLSearchParams(params); detailParams.set("from", "audit");
    return `/audit/${encodeURIComponent(audit.user.login)}/repositories/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}?${detailParams.toString()}`;
  };
  const summary: Array<[string, number]> = [["Repositories", audit.summary.repositoryCount], ["Original", audit.summary.originalCount], ["Forks", audit.summary.forkCount], ["Showcase", audit.summary.classifications.SHOWCASE], ["Keep", audit.summary.classifications.KEEP], ["Archive", audit.summary.classifications.ARCHIVE], ["Fork review", audit.summary.classifications.FORK_REVIEW], ["Review", audit.summary.classifications.REVIEW], ["Cleanup", audit.summary.classifications.CLEANUP]];
  return <div className="container-page pb-20 pt-8"><section className="overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-soft"><div className="grid gap-5 border-b p-5 sm:p-7 lg:grid-cols-[1fr_auto] lg:items-center"><div className="flex min-w-0 items-center gap-4"><img src={audit.user.avatarUrl} alt="" className="h-14 w-14 rounded-2xl" /><div className="min-w-0"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-cobalt-600">Public GitHub audit</p><h1 className="truncate text-2xl font-semibold">{audit.user.name ?? audit.user.login}</h1><p className="text-sm text-slate-500">@{audit.user.login}</p></div></div><div className="flex flex-wrap gap-2"><button type="button" onClick={onRefresh} className="rounded-xl border px-4 py-2 text-xs font-semibold">Refresh audit</button><Link to={`/audit/${audit.user.login}/prepare`} className="rounded-xl bg-cobalt-600 px-4 py-2 text-xs font-semibold text-white">Prepare my GitHub →</Link><Link to={`/career/${audit.user.login}`} className="rounded-xl bg-ink px-4 py-2 text-xs font-semibold text-white">Build career profile →</Link></div></div><div className="grid gap-px bg-slate-200 lg:grid-cols-[250px_1fr]"><div className="bg-cobalt-950 p-7 text-white"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-white/50">Portfolio health</p><p className="mt-4 text-6xl font-semibold">{audit.summary.portfolio.score}<span className="text-lg text-lime-300">/100</span></p><p className="mt-4 text-xs text-white/60">Public repository evidence summary</p><p className="mt-6 border-t border-white/10 pt-4 text-xs">Evidence coverage <strong>{audit.summary.explanationCoverage}%</strong></p></div><div className="grid grid-cols-2 gap-px bg-slate-200 sm:grid-cols-3">{summary.map(([label, value], index) => <div key={label} className={`bg-white p-5 ${index === summary.length - 1 ? "col-span-2 sm:col-span-1" : ""}`}><p className="text-2xl font-semibold">{value}</p><p className="text-xs text-slate-500">{label}</p></div>)}</div></div></section>
    <div className="mt-5 rounded-2xl border border-cobalt-100 bg-cobalt-50 p-4"><div className="flex gap-3"><ShieldIcon className="h-5 w-5 text-cobalt-600" /><p className="text-xs leading-5 text-slate-600"><strong>Read-only and explainable.</strong> Open any repository for its exact score, evidence trace, unknown signals, README enrichment state, and local decision controls.</p></div></div>
    <section className="mt-10"><p className="eyebrow">Repository evidence</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em]">Review every recommendation.</h2><div className="mt-6 grid gap-3 lg:grid-cols-[1fr_auto]"><label className="relative"><span className="sr-only">Search repositories</span><SearchIcon className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={view.query} onChange={(event) => update({ query: event.target.value })} placeholder="Search repositories" className="min-h-10 w-full rounded-xl border bg-white py-2 pl-9 pr-3 text-sm" /></label><label><span className="sr-only">Sort repositories</span><select value={view.sort} onChange={(event) => update({ sort: event.target.value as RepositorySort })} className="min-h-10 w-full rounded-xl border bg-white px-3 text-sm"><option value="score">Highest score</option><option value="updated">Recently active</option><option value="stars">Most stars</option><option value="name">Name A–Z</option><option value="classification">Classification</option></select></label></div><div className="mt-4 flex flex-wrap gap-2">{classificationOrder.map((filter) => <button key={filter} type="button" onClick={() => update({ filter })} aria-pressed={view.filter === filter} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${view.filter === filter ? "bg-ink text-white" : "bg-white text-slate-600"}`}>{labels[filter]} <span className="opacity-60">{filter === "ALL" ? audit.repositories.length : audit.summary.classifications[filter]}</span></button>)}</div>
      {!visible.length ? <div className="mt-5 rounded-2xl border border-dashed bg-white p-10 text-center"><p className="font-semibold">No repositories match this view.</p></div> : <><div className="mt-5 hidden overflow-hidden rounded-2xl border bg-white md:block"><table className="w-full table-fixed text-left"><thead className="border-b bg-slate-50 text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="w-[27%] px-4 py-3">Repository</th><th className="w-[14%] px-3 py-3">Class</th><th className="w-[8%] px-3 py-3">Score</th><th className="w-[11%] px-3 py-3">Language</th><th className="w-[14%] px-3 py-3">Activity</th><th className="w-[7%] px-3 py-3">Stars</th><th className="px-3 py-3">Reason</th></tr></thead><tbody className="divide-y">{displayed.map((item) => <tr key={item.repository.id} className="hover:bg-slate-50"><td className="px-4 py-4"><Link to={detailUrl(item.repository.owner, item.repository.name)} className="flex items-center gap-2 font-mono text-xs font-semibold text-cobalt-700 hover:underline"><GitBranchIcon className="h-4 w-4" />{item.repository.name}</Link><p className="mt-1 text-[10px] text-slate-400">{item.repository.isFork ? "Fork" : "Original"}</p></td><td className="px-3"><Badge value={item.result.classification} /></td><td className="px-3 font-mono font-bold">{item.result.score}</td><td className="truncate px-3 text-xs">{item.repository.primaryLanguage ?? "Unknown"}</td><td className="px-3 text-xs">{date(item.repository.pushedAt)}</td><td className="px-3 text-xs">{item.repository.stars}</td><td className="px-3 text-xs leading-5 text-slate-500"><span className="line-clamp-2">{item.result.classificationReason}</span></td></tr>)}</tbody></table></div><div className="mt-5 grid gap-3 md:hidden">{displayed.map((item) => <Link key={item.repository.id} to={detailUrl(item.repository.owner, item.repository.name)} className="rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><p className="truncate font-mono text-sm font-semibold text-cobalt-700">{item.repository.name}</p><span className="font-mono text-xl font-bold">{item.result.score}</span></div><div className="mt-3"><Badge value={item.result.classification} /></div><p className="mt-3 line-clamp-2 text-xs leading-5 text-slate-500">{item.result.classificationReason}</p></Link>)}</div>{displayed.length < visible.length ? <div className="mt-5 text-center"><button type="button" onClick={() => setLimit((value) => value + 100)} className="rounded-xl border bg-white px-5 py-3 text-sm font-semibold">Show 100 more ({visible.length - displayed.length} remaining)</button></div> : null}</>}
    </section></div>;
}
