import type { GitHubRepositorySnapshot } from "../../domain/github";
import {
  PORTFOLIO_HEALTH_VERSION,
  REPOSITORY_SCORE_VERSION,
  type PortfolioHealthScore,
  type RepositoryClassification,
  type RepositoryScore,
  type ScoreReason,
  type ScoreSignalKey,
} from "../../domain/scoring";

interface FactorResult {
  signal: ScoreSignalKey;
  points: number;
  maximum: number;
  observedValue: string | number | boolean | null;
  explanation: string;
}

function clamp(value: number, minimum = 0, maximum = 100): number {
  return Math.min(maximum, Math.max(minimum, value));
}

function roundHalfUp(value: number): number {
  return Math.floor(value + 0.5);
}

function elapsedDays(from: string, to: string): number | null {
  const fromTime = Date.parse(from);
  const toTime = Date.parse(to);
  if (!Number.isFinite(fromTime) || !Number.isFinite(toTime) || fromTime > toTime) return null;
  return Math.floor((toTime - fromTime) / 86_400_000);
}

function activityPoints(days: number): number {
  if (days <= 30) return 18;
  if (days <= 90) return 15;
  if (days <= 180) return 11;
  if (days <= 365) return 7;
  if (days <= 730) return 3;
  return 0;
}

function maturityPoints(days: number): number {
  if (days < 14) return 1;
  if (days < 90) return 3;
  if (days <= 730) return 5;
  return 4;
}

function starsPoints(stars: number): number {
  if (stars === 0) return 0;
  if (stars <= 2) return 2;
  if (stars <= 9) return 4;
  if (stars <= 49) return 6;
  return 7;
}

function forksPoints(forks: number): number {
  if (forks === 0) return 0;
  if (forks <= 2) return 1;
  if (forks <= 9) return 2;
  return 3;
}

function descriptionPoints(description?: string): number {
  if (!description || description.trim().length < 10) return 0;
  const length = description.trim().length;
  let points = length < 40 ? 4 : length <= 120 ? 8 : length <= 200 ? 10 : 8;
  if (/^(my project|test|todo|hello world|created with|generated by)\.?$/i.test(description.trim())) points = Math.max(0, points - 2);
  return points;
}

function topicsPoints(topics: string[]): number {
  const count = new Set(topics.map((topic) => topic.toLowerCase())).size;
  if (count === 0) return 0;
  if (count === 1) return 3;
  if (count === 2) return 5;
  return 7;
}

function classificationFor(
  repository: GitHubRepositorySnapshot,
  score: number,
  availableMaximum: number,
  pushedDays: number | null,
  ageDays: number | null,
): { classification: RepositoryClassification; reason: string } {
  if (repository.isFork) return { classification: "FORK_REVIEW", reason: "This is a fork, so it needs manual review before being treated as portfolio evidence." };
  if (repository.isArchived) return { classification: "ARCHIVE", reason: "This repository is already archived and is shown as historical evidence." };
  if (pushedDays !== null && pushedDays > 730 && score < 40 && repository.stars < 3 && repository.forks < 2) return { classification: "ARCHIVE", reason: "Limited recent activity, limited public engagement, and a low evidence score make this a candidate to consider archiving." };
  if (pushedDays !== null && pushedDays > 730 && score < 50 && (repository.stars >= 3 || repository.forks >= 2)) return { classification: "REVIEW", reason: "This repository is older but has meaningful public engagement, so its historical relevance should be reviewed manually rather than reduced to an archive recommendation." };
  if (availableMaximum < 55 || ageDays === null || (ageDays !== null && ageDays < 14)) return { classification: "REVIEW", reason: "The available public evidence is incomplete or too recent for a confident recommendation." };
  if (score >= 70 && (repository.description?.length ?? 0) >= 40 && repository.hasReadme === true) return { classification: "SHOWCASE", reason: "Strong public metadata, recent evidence, and confirmed documentation make this a showcase candidate." };
  if (score >= 50) return { classification: "KEEP", reason: "The available public evidence supports keeping this repository visible, though improvements may still help." };
  if (pushedDays !== null && pushedDays <= 730) return { classification: "CLEANUP", reason: "This repository is active enough to improve, but its public portfolio evidence has clear gaps." };
  return { classification: "REVIEW", reason: "The signals are mixed, so a manual review is more appropriate than an automatic recommendation." };
}

export function scoreRepository(repository: GitHubRepositorySnapshot, auditAt: string): RepositoryScore {
  const factors: FactorResult[] = [];
  const unknownSignals: ScoreSignalKey[] = [];
  const pushedDays = repository.pushedAt ? elapsedDays(repository.pushedAt, auditAt) : null;
  const ageDays = elapsedDays(repository.createdAt, auditAt);

  factors.push({ signal: "original_repository", points: repository.isFork ? 0 : 8, maximum: 8, observedValue: !repository.isFork, explanation: repository.isFork ? "This repository is a fork and may represent learning or contribution evidence." : "This repository is owned as an original repository." });

  if (pushedDays === null) unknownSignals.push("recent_push");
  else factors.push({ signal: "recent_push", points: activityPoints(pushedDays), maximum: 18, observedValue: pushedDays, explanation: `The latest public push was ${pushedDays} day${pushedDays === 1 ? "" : "s"} before this audit.` });

  if (ageDays === null) unknownSignals.push("repository_maturity");
  else factors.push({ signal: "repository_maturity", points: maturityPoints(ageDays), maximum: 5, observedValue: ageDays, explanation: `The repository has ${ageDays} days of public history.` });

  factors.push(
    { signal: "stars", points: starsPoints(repository.stars), maximum: 7, observedValue: repository.stars, explanation: `${repository.stars} public star${repository.stars === 1 ? "" : "s"} observed. Engagement is only one portfolio signal.` },
    { signal: "forks", points: forksPoints(repository.forks), maximum: 3, observedValue: repository.forks, explanation: `${repository.forks} public fork${repository.forks === 1 ? "" : "s"} received.` },
    { signal: "description_quality", points: descriptionPoints(repository.description), maximum: 10, observedValue: repository.description ?? null, explanation: repository.description ? "A public repository description is available and scored by clarity and length." : "No public repository description was observed." },
  );

  if (repository.hasReadme === undefined) unknownSignals.push("readme_presence");
  else factors.push({ signal: "readme_presence", points: repository.hasReadme ? 15 : 0, maximum: 15, observedValue: repository.hasReadme, explanation: repository.hasReadme ? "A README was confirmed through a targeted request." : "A targeted request confirmed that no README is available on the default branch." });

  const hasLicense = Boolean(repository.licenseSpdxId && repository.licenseSpdxId !== "NOASSERTION");
  factors.push(
    { signal: "license_presence", points: hasLicense ? 5 : 0, maximum: 5, observedValue: repository.licenseSpdxId ?? null, explanation: hasLicense ? "A recognized public license is present." : "No recognized public license was observed in repository metadata." },
    { signal: "topics_presence", points: topicsPoints(repository.topics), maximum: 7, observedValue: repository.topics.length, explanation: repository.topics.length ? `${repository.topics.length} topic${repository.topics.length === 1 ? "" : "s"} help describe the repository.` : "No repository topics were observed." },
  );

  unknownSignals.push("release_activity", "issues_activity", "pull_request_activity");

  let completenessMaximum = 4;
  let completenessPoints = (repository.description && repository.description.length >= 40 ? 2 : 0) + (repository.homepageUrl ? 2 : 0);
  const completenessKnown: string[] = ["description", "homepage"];
  if (repository.hasReadme !== undefined) {
    completenessMaximum += 2;
    completenessKnown.push("README");
    if (repository.hasReadme) completenessPoints += 2;
  }
  if (repository.isArchived) {
    completenessMaximum += 2;
    completenessKnown.push("archived completion state");
    completenessPoints += 2;
  }
  factors.push({ signal: "project_completeness", points: completenessPoints, maximum: completenessMaximum, observedValue: `${completenessPoints}/${completenessMaximum}`, explanation: `Completeness is partially scored from known signals: ${completenessKnown.join(", ")}. Unfetched signals are excluded.` });

  const availablePositivePoints = factors.reduce((total, factor) => total + factor.maximum, 0);
  const earnedPositivePoints = factors.reduce((total, factor) => total + factor.points, 0);
  const normalizedPositive = availablePositivePoints ? roundHalfUp((earnedPositivePoints / availablePositivePoints) * 100) : 0;

  const penalties: ScoreReason[] = [];
  if (repository.isArchived) penalties.push({ signal: "archived_repository", points: -35, observedValue: true, explanation: "Archived repositories are treated as historical rather than active portfolio work." });
  if (repository.isFork) penalties.push({ signal: "fork_repository", points: -20, observedValue: true, explanation: "Forks need manual review because ownership and contribution depth cannot be inferred from listing metadata." });
  if (!repository.isFork && !repository.isArchived && pushedDays !== null && pushedDays > 365) {
    const penalty = pushedDays > 730 ? -10 : -5;
    penalties.push({ signal: "stale_repository", points: penalty, observedValue: pushedDays, explanation: "Older public push activity reduces current portfolio relevance; it does not imply anything about private or professional work." });
  }

  const score = clamp(normalizedPositive + penalties.reduce((total, reason) => total + reason.points, 0));
  const classification = classificationFor(repository, score, availablePositivePoints, pushedDays, ageDays);
  const reasons: ScoreReason[] = factors.map((factor) => ({
    signal: factor.signal,
    points: factor.points,
    observedValue: factor.observedValue,
    explanation: factor.explanation,
  })).concat(penalties);
  const confidence = availablePositivePoints >= 75 && repository.hasReadme !== undefined && pushedDays !== null ? "high" : availablePositivePoints >= 55 ? "medium" : "low";

  return {
    version: REPOSITORY_SCORE_VERSION,
    repositoryId: repository.id,
    auditAt,
    score,
    availablePositivePoints,
    classification: classification.classification,
    classificationReason: classification.reason,
    confidence,
    reasons,
    unknownSignals: [...new Set(unknownSignals)],
    warnings: ["This is a public repository evidence score—not a measure of engineering ability, employability, or developer quality."],
  };
}

export interface ScoredRepository {
  repository: GitHubRepositorySnapshot;
  result: RepositoryScore;
}

export interface AuditSummary {
  portfolio: PortfolioHealthScore;
  repositoryCount: number;
  originalCount: number;
  forkCount: number;
  activeCount: number;
  inactiveCount: number;
  explanationCoverage: number;
  classifications: Record<RepositoryClassification, number>;
}

function average(values: number[]): number {
  return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
}

export function calculateAuditSummary(scored: ScoredRepository[], auditAt: string): AuditSummary {
  const eligible = scored.filter(({ repository }) => !repository.isFork && !repository.isArchived);
  const topScores = eligible.map(({ result }) => result.score).sort((a, b) => b - a).slice(0, 6);
  const knownReadmes = eligible.filter(({ repository }) => repository.hasReadme !== undefined);
  const documentationCoverage = knownReadmes.length ? average(knownReadmes.map(({ repository }) => repository.hasReadme ? 100 : 0)) : 0;
  const metadataCoverage = average(eligible.map(({ repository }) => {
    const checks = [Boolean(repository.description && repository.description.length >= 40), repository.topics.length > 0, Boolean(repository.licenseSpdxId && repository.licenseSpdxId !== "NOASSERTION")];
    return (checks.filter(Boolean).length / checks.length) * 100;
  }));
  const recentTwenty = [...eligible].sort((a, b) => Date.parse(b.repository.pushedAt ?? "") - Date.parse(a.repository.pushedAt ?? "")).slice(0, 20);
  const maintenanceHealth = average(recentTwenty.map(({ repository }) => {
    const days = repository.pushedAt ? elapsedDays(repository.pushedAt, auditAt) : null;
    return days !== null && days <= 365 ? 100 : 0;
  }));
  const showcaseCount = scored.filter(({ result }) => result.classification === "SHOWCASE").length;
  const portfolioFocus = showcaseCount >= 3 && showcaseCount <= 6 ? 100 : showcaseCount >= 1 && showcaseCount <= 10 ? 80 : showcaseCount <= 15 && showcaseCount > 0 ? 60 : showcaseCount > 15 ? 40 : eligible.length ? 30 : 0;
  const showcaseQuality = average(topScores);
  const portfolioScore = roundHalfUp(showcaseQuality * 0.35 + documentationCoverage * 0.2 + metadataCoverage * 0.15 + maintenanceHealth * 0.15 + portfolioFocus * 0.15);
  const classifications: Record<RepositoryClassification, number> = { SHOWCASE: 0, KEEP: 0, ARCHIVE: 0, FORK_REVIEW: 0, REVIEW: 0, CLEANUP: 0 };
  scored.forEach(({ result }) => { classifications[result.classification] += 1; });
  const activeCount = scored.filter(({ repository }) => {
    const days = repository.pushedAt ? elapsedDays(repository.pushedAt, auditAt) : null;
    return days !== null && days <= 365;
  }).length;

  return {
    portfolio: {
      version: PORTFOLIO_HEALTH_VERSION,
      score: clamp(portfolioScore),
      breakdown: {
        showcaseQuality: roundHalfUp(showcaseQuality),
        documentationCoverage: roundHalfUp(documentationCoverage),
        metadataCoverage: roundHalfUp(metadataCoverage),
        maintenanceHealth: roundHalfUp(maintenanceHealth),
        portfolioFocus,
      },
      explanations: [
        "Portfolio health summarizes visible public repository evidence, not developer ability.",
        knownReadmes.length < eligible.length ? `README evidence was checked for ${knownReadmes.length} of ${eligible.length} eligible repositories; unknown repositories are not treated as missing documentation.` : "README evidence is available for all eligible repositories.",
      ],
    },
    repositoryCount: scored.length,
    originalCount: scored.filter(({ repository }) => !repository.isFork).length,
    forkCount: scored.filter(({ repository }) => repository.isFork).length,
    activeCount,
    inactiveCount: scored.length - activeCount,
    explanationCoverage: roundHalfUp(average(scored.map(({ result }) => result.availablePositivePoints))),
    classifications,
  };
}
