import { useState, type ChangeEvent, type ReactNode } from "react";
import { Link, useSearchParams } from "react-router-dom";
import type { CareerEvidenceProfile, CareerRecord, CareerSection, EvidenceProvenance, ResumeReviewItem } from "../../domain/career-evidence-profile";
import type { GitHubAudit } from "../github-audit/run-audit";
import { FileIcon, ShieldIcon } from "../../components/icons";
import { acceptReviewItem, addManualReviewItem, attachResume, clearResumeEvidence, editReviewItem, removeReviewItem, updateAcceptedRecord, updateProfileField } from "./career-profile";
import { MAX_RESUME_FILE_BYTES, processPastedResume, processResumeFile, ResumeProcessingError } from "./resume-processing";

interface Props {
  audit: GitHubAudit;
  profile: CareerEvidenceProfile;
  setProfile: (profile: CareerEvidenceProfile | ((current: CareerEvidenceProfile) => CareerEvidenceProfile)) => void;
  saved: boolean;
  onClearGitHubData: () => void;
  onClearCareerProfile: () => void;
  onClearAll: () => void;
}

type Step = "resume" | "review" | "profile" | "compare" | "preview";
const sections: CareerSection[] = ["experience", "education", "skills", "projects", "certifications", "achievements", "professionalLinks", "other"];
const sectionLabels: Record<CareerSection, string> = { experience: "Experience", education: "Education", skills: "Skills", projects: "Projects", certifications: "Certifications", achievements: "Achievements", professionalLinks: "Professional links", other: "Other information" };

function SourceBadge({ source }: { source: EvidenceProvenance }) {
  const config = {
    GITHUB_OBSERVED: ["GitHub observed", "border-lime-200 bg-lime-50 text-lime-900"],
    RESUME_PROVIDED: ["Resume", "border-cobalt-100 bg-cobalt-50 text-cobalt-700"],
    USER_PROVIDED: ["You", "border-violet-200 bg-violet-50 text-violet-700"],
    DERIVED: ["Derived", "border-slate-200 bg-slate-50 text-slate-600"],
  } as const;
  return <span className={`inline-flex rounded-md border px-2 py-1 font-mono text-[9px] font-bold uppercase tracking-wide ${config[source][1]}`}>{config[source][0]}</span>;
}

function Panel({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <div className={`rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 ${className}`}>{children}</div>;
}

function ResumeInput({ profile, setProfile, goNext }: Pick<Props, "profile" | "setProfile"> & { goNext: () => void }) {
  const [pastedText, setPastedText] = useState(profile.resumeEvidence?.fileType === "PASTED_TEXT" ? profile.resumeEvidence.text : "");
  const [processing, setProcessing] = useState(false);
  const [error, setError] = useState("");

  async function handleFile(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    setProcessing(true); setError("");
    try {
      const result = await processResumeFile(file);
      setProfile((current) => attachResume(clearResumeEvidence(current), result.document, result.items));
      goNext();
    } catch (caught) {
      setError(caught instanceof ResumeProcessingError ? caught.message : "The resume could not be processed locally. Paste the text instead.");
    } finally { setProcessing(false); event.target.value = ""; }
  }

  function handlePaste() {
    setProcessing(true); setError("");
    try {
      const result = processPastedResume(pastedText);
      setProfile((current) => attachResume(clearResumeEvidence(current), result.document, result.items));
      goNext();
    } catch (caught) {
      setError(caught instanceof ResumeProcessingError ? caught.message : "The pasted resume could not be processed.");
    } finally { setProcessing(false); }
  }

  return <section aria-labelledby="resume-input-title"><p className="eyebrow">Step 1 · Resume</p><h2 id="resume-input-title" className="mt-3 text-3xl font-semibold tracking-[-.04em]">Add private career context.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Upload a supported file or paste resume text. Extraction is deterministic and nothing becomes an accepted fact until you review it.</p>
    <div className="mt-6 flex gap-3 rounded-2xl border border-lime-200 bg-lime-50 p-4"><ShieldIcon className="h-5 w-5 shrink-0 text-lime-900" /><div><p className="text-sm font-semibold text-lime-950">Your resume stays in your browser.</p><p className="mt-1 text-xs leading-5 text-lime-900/70">No AI, external resume API, server upload, account, or database is used.</p></div></div>
    {profile.resumeEvidence ? <Panel className="mt-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><FileIcon className="h-5 w-5 text-cobalt-600" /><p className="font-semibold">Resume loaded locally</p></div><p className="mt-2 text-xs text-slate-500">{profile.resumeEvidence.fileName ?? "Pasted text"} · {profile.resumeEvidence.fileType} · {profile.resumeReview.length} extracted item(s)</p></div><div className="flex gap-2"><button type="button" onClick={goNext} className="rounded-xl bg-cobalt-600 px-4 py-2 text-sm font-semibold text-white">Review evidence</button><button type="button" onClick={() => { setProfile((current) => clearResumeEvidence(current)); setPastedText(""); }} className="rounded-xl border border-red-200 px-4 py-2 text-sm font-semibold text-red-700">Clear resume</button></div></div></Panel> : null}
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><Panel><p className="font-mono text-[10px] font-bold uppercase tracking-[.14em] text-cobalt-600">Upload resume</p><h3 className="mt-3 text-lg font-semibold">PDF, DOCX, or TXT</h3><p className="mt-2 text-xs leading-5 text-slate-500">Maximum 5 MB. Files are parsed in this browser. Image-only PDFs may require the paste fallback.</p><label className="mt-6 flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-slate-300 bg-slate-50 p-5 text-center hover:border-cobalt-400"><FileIcon className="h-6 w-6 text-cobalt-600" /><span className="mt-2 text-sm font-semibold">{processing ? "Processing locally…" : "Choose resume file"}</span><span className="mt-1 text-[10px] text-slate-400">PDF · DOCX · TXT · up to {MAX_RESUME_FILE_BYTES / 1024 / 1024} MB</span><input className="sr-only" type="file" accept=".pdf,.docx,.txt,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,text/plain" onChange={handleFile} disabled={processing} /></label></Panel>
      <Panel><p className="font-mono text-[10px] font-bold uppercase tracking-[.14em] text-cobalt-600">Paste fallback</p><h3 className="mt-3 text-lg font-semibold">Paste resume text</h3><textarea aria-label="Paste resume text" value={pastedText} onChange={(event) => setPastedText(event.target.value)} rows={8} placeholder="Paste your resume text here…" className="mt-4 w-full rounded-xl border border-slate-300 p-3 text-sm" /><button type="button" onClick={handlePaste} disabled={processing} className="mt-3 w-full rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">Extract for review</button></Panel></div>
    {error ? <div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><strong>Resume processing stopped.</strong> {error} Paste the resume text to continue.</div> : null}
  </section>;
}

function ReviewCard({ item, profile, setProfile }: { item: ResumeReviewItem; profile: CareerEvidenceProfile; setProfile: Props["setProfile"] }) {
  const accepted = item.status === "ACCEPTED";
  function update(key: keyof ResumeReviewItem, value: string | string[]) { setProfile(editReviewItem(profile, item.id, { [key]: value })); }
  return <article className={`rounded-xl border p-4 ${accepted ? "border-lime-200 bg-lime-50/40" : "border-slate-200 bg-white"}`}><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><SourceBadge source={item.provenance.source} />{accepted ? <span className="text-[10px] font-semibold text-lime-800">Accepted</span> : <span className="text-[10px] text-slate-400">Review required</span>}</div><button type="button" onClick={() => setProfile(removeReviewItem(profile, item.id))} className="text-xs font-semibold text-red-700">Remove</button></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-2"><label><span className="text-[10px] font-semibold">Title / skill / label</span><input value={item.title} onChange={(event) => update("title", event.target.value)} className="mt-1 min-h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" /></label>{item.section !== "skills" && item.section !== "achievements" && item.section !== "other" ? <label><span className="text-[10px] font-semibold">Organization / issuer</span><input value={item.organization} onChange={(event) => update("organization", event.target.value)} className="mt-1 min-h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" /></label> : null}{item.section !== "skills" ? <label className="sm:col-span-2"><span className="text-[10px] font-semibold">Description</span><textarea value={item.description} onChange={(event) => update("description", event.target.value)} rows={2} className="mt-1 w-full rounded-lg border border-slate-300 p-3 text-sm" /></label> : null}{item.section === "experience" || item.section === "education" ? <><label><span className="text-[10px] font-semibold">Start date</span><input value={item.startDate} onChange={(event) => update("startDate", event.target.value)} className="mt-1 min-h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" /></label><label><span className="text-[10px] font-semibold">End date</span><input value={item.endDate} onChange={(event) => update("endDate", event.target.value)} className="mt-1 min-h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" /></label></> : null}{item.section === "experience" || item.section === "projects" ? <label className="sm:col-span-2"><span className="text-[10px] font-semibold">Technologies, comma-separated</span><input value={item.technologies.join(", ")} onChange={(event) => update("technologies", event.target.value.split(",").map((value) => value.trim()).filter(Boolean))} className="mt-1 min-h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" /></label> : null}{item.section === "professionalLinks" || item.section === "projects" || item.section === "certifications" ? <label className="sm:col-span-2"><span className="text-[10px] font-semibold">URL</span><input value={item.url} onChange={(event) => update("url", event.target.value)} className="mt-1 min-h-10 w-full rounded-lg border border-slate-300 px-3 text-sm" /></label> : null}</div>
    {!accepted ? <button type="button" onClick={() => setProfile(acceptReviewItem(profile, item.id))} disabled={!item.title.trim() && !item.description.trim()} className="mt-4 rounded-lg bg-cobalt-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-40">Accept item</button> : <p className="mt-3 text-[10px] text-slate-500">Edits after acceptance should be made in the profile preview and become Source: You.</p>}
  </article>;
}

function ResumeReview({ profile, setProfile, goNext }: Pick<Props, "profile" | "setProfile"> & { goNext: () => void }) {
  const [filter, setFilter] = useState<CareerSection | "all">("all");
  const visible = profile.resumeReview.filter((item) => filter === "all" || item.section === filter);
  const accepted = profile.resumeReview.filter((item) => item.status === "ACCEPTED").length;
  return <section aria-labelledby="resume-review-title"><p className="eyebrow">Step 2 · Review</p><h2 id="resume-review-title" className="mt-3 text-3xl font-semibold tracking-[-.04em]">Review extracted evidence.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Nothing is accepted silently. Correct, accept, remove, or add every item. Editing an extraction changes its source to You.</p><div className="mt-5 flex flex-wrap items-center gap-2"><button type="button" onClick={() => setFilter("all")} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${filter === "all" ? "bg-ink text-white" : "bg-white"}`}>All {profile.resumeReview.length}</button>{sections.map((section) => <button key={section} type="button" onClick={() => setFilter(section)} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${filter === section ? "bg-ink text-white" : "bg-white"}`}>{sectionLabels[section]} {profile.resumeReview.filter((item) => item.section === section).length}</button>)}</div>
    <div className="mt-5 rounded-xl border border-cobalt-100 bg-cobalt-50 px-4 py-3 text-xs text-cobalt-800">{accepted} of {profile.resumeReview.length} extracted item(s) accepted.</div>
    <div className="mt-5 grid gap-4 lg:grid-cols-2">{visible.map((item) => <ReviewCard key={item.id} item={item} profile={profile} setProfile={setProfile} />)}</div>
    {!visible.length ? <Panel className="mt-5 text-center"><p className="text-sm text-slate-500">No items in this section. Add one manually below.</p></Panel> : null}
    <div className="mt-6 flex flex-wrap gap-2"><span className="text-xs font-semibold text-slate-500">Manual addition:</span>{sections.map((section) => <button key={section} type="button" onClick={() => { setProfile(addManualReviewItem(profile, section)); setFilter(section); }} className="rounded-lg border border-slate-300 bg-white px-3 py-1.5 text-xs">+ {sectionLabels[section]}</button>)}</div>
    <div className="mt-10 flex justify-end"><button type="button" onClick={goNext} className="rounded-xl bg-cobalt-600 px-5 py-3 text-sm font-semibold text-white">Continue to profile →</button></div>
  </section>;
}

function UserProfileForm({ profile, setProfile, goNext }: Pick<Props, "profile" | "setProfile"> & { goNext: () => void }) {
  const fields: Array<{ group: "identity" | "careerDirection"; key: string; label: string; type?: string; multiline?: boolean }> = [
    { group: "careerDirection", key: "professionalHeadline", label: "Professional headline" }, { group: "careerDirection", key: "currentRole", label: "Current role" },
    { group: "careerDirection", key: "targetRole", label: "Target role" }, { group: "careerDirection", key: "careerDirection", label: "Career direction", multiline: true },
    { group: "careerDirection", key: "shortIntroduction", label: "Short introduction", multiline: true }, { group: "careerDirection", key: "yearsOfExperience", label: "Years of experience" },
    { group: "careerDirection", key: "preferredTechnologies", label: "Preferred technologies, comma-separated" }, { group: "identity", key: "location", label: "Location" },
    { group: "identity", key: "linkedin", label: "LinkedIn", type: "url" }, { group: "identity", key: "website", label: "Website", type: "url" },
    { group: "identity", key: "email", label: "Email", type: "email" }, { group: "identity", key: "otherInformation", label: "Other professional information", multiline: true },
  ];
  const getValue = (group: "identity" | "careerDirection", key: string): string => {
    const item = (profile[group] as Record<string, { value: string | string[] } | undefined>)[key];
    return Array.isArray(item?.value) ? item.value.join(", ") : item?.value ?? "";
  };
  return <section aria-labelledby="career-context-title"><p className="eyebrow">Step 3 · Profile</p><h2 id="career-context-title" className="mt-3 text-3xl font-semibold tracking-[-.04em]">Add information only you can provide.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Career direction and professional context are never inferred from GitHub. Every field below is Source: You.</p><Panel className="mt-6"><div className="flex items-center gap-2"><SourceBadge source="USER_PROVIDED" /><p className="text-xs text-slate-500">Explicit information under your control</p></div><div className="mt-5 grid gap-5 sm:grid-cols-2">{fields.map((field) => <label key={`${field.group}-${field.key}`} className={field.multiline ? "sm:col-span-2" : ""}><span className="text-xs font-semibold">{field.label}</span>{field.multiline ? <textarea rows={3} value={getValue(field.group, field.key)} onChange={(event) => setProfile((current) => updateProfileField(current, field.group, field.key, event.target.value))} className="mt-2 w-full rounded-xl border border-slate-300 p-3 text-sm" /> : <input type={field.type ?? "text"} value={getValue(field.group, field.key)} onChange={(event) => setProfile((current) => updateProfileField(current, field.group, field.key, field.key === "preferredTechnologies" ? event.target.value.split(",").map((value) => value.trim()).filter(Boolean) : event.target.value))} className="mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm" />}</label>)}</div></Panel><div className="mt-10 flex justify-end"><button type="button" onClick={goNext} className="rounded-xl bg-cobalt-600 px-5 py-3 text-sm font-semibold text-white">Compare evidence →</button></div></section>;
}

function ComparisonView({ profile, goNext }: { profile: CareerEvidenceProfile; goNext: () => void }) {
  const skills = profile.derived.comparisons.filter((item) => item.result === "MULTIPLE_SOURCE_SUPPORT" || item.result === "RESUME_ONLY" || item.result === "GITHUB_ONLY");
  const opportunities = profile.derived.comparisons.filter((item) => item.result === "POTENTIAL_RESUME_OPPORTUNITY");
  const resultLabel = { MULTIPLE_SOURCE_SUPPORT: "Multiple-source support", RESUME_ONLY: "Resume only", GITHUB_ONLY: "GitHub only", POTENTIAL_RESUME_OPPORTUNITY: "Potential resume opportunity" } as const;
  return <section aria-labelledby="comparison-title"><p className="eyebrow">Step 4 · Compare</p><h2 id="comparison-title" className="mt-3 text-3xl font-semibold tracking-[-.04em]">Compare evidence without judging claims.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Public GitHub evidence not detected does not mean a skill is absent. It only describes what this public evidence set supports.</p>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(profile.derived.sourceCoverage).map(([key, value]) => <Panel key={key}><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{key.replace(/([A-Z])/g, " $1")}</p><p className="mt-2 text-xl font-semibold">{typeof value === "number" ? value : value.charAt(0) + value.slice(1).toLowerCase()}</p></Panel>)}</div>
    <div className="mt-8 grid gap-6 lg:grid-cols-2"><div><h3 className="text-lg font-semibold">Skill evidence</h3><div className="mt-3 space-y-3">{skills.map((item) => <Panel key={item.id}><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">{item.subject}</p><SourceBadge source="DERIVED" /></div><p className="mt-2 text-xs font-semibold text-cobalt-700">{resultLabel[item.result]}</p><p className="mt-2 text-xs leading-5 text-slate-600">{item.explanation}</p>{item.result === "RESUME_ONLY" ? <p className="mt-2 text-[10px] text-slate-400">This is not a truth or expertise judgment.</p> : null}</Panel>)}{!skills.length ? <Panel><p className="text-sm text-slate-500">Accept resume skills or select GitHub portfolio projects to compare evidence.</p></Panel> : null}</div></div><div><h3 className="text-lg font-semibold">GitHub → resume opportunities</h3><div className="mt-3 space-y-3">{opportunities.map((item) => <Panel key={item.id}><div className="flex items-center justify-between gap-2"><p className="font-mono text-sm font-semibold">{item.subject}</p><SourceBadge source="DERIVED" /></div><p className="mt-2 text-xs font-semibold text-cobalt-700">Potential resume opportunity</p><p className="mt-2 text-xs leading-5 text-slate-600">{item.explanation}</p></Panel>)}{!opportunities.length ? <Panel><p className="text-sm text-slate-500">No selected GitHub project gap was detected.</p></Panel> : null}</div></div></div>
    <div className="mt-10 flex justify-end"><button type="button" onClick={goNext} className="rounded-xl bg-cobalt-600 px-5 py-3 text-sm font-semibold text-white">Open career profile →</button></div>
  </section>;
}

function RecordEditor({ record, section, setProfile }: { record: CareerRecord; section: Exclude<CareerSection, "skills">; setProfile: Props["setProfile"] }) {
  return <article className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-2"><SourceBadge source={record.provenance[0]?.source ?? "USER_PROVIDED"} /><span className="text-[10px] text-slate-400">Editable</span></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><input aria-label={`${section} title`} value={record.title} onChange={(event) => setProfile((current) => updateAcceptedRecord(current, section, record.id, { title: event.target.value }))} className="min-h-9 rounded-lg border px-2 text-sm font-semibold" /><input aria-label={`${section} organization`} value={record.organization ?? ""} onChange={(event) => setProfile((current) => updateAcceptedRecord(current, section, record.id, { organization: event.target.value }))} placeholder="Organization" className="min-h-9 rounded-lg border px-2 text-sm" />{section === "experience" || section === "education" ? <><input aria-label={`${section} start date`} value={record.startDate ?? ""} onChange={(event) => setProfile((current) => updateAcceptedRecord(current, section, record.id, { startDate: event.target.value }))} placeholder="Start date" className="min-h-9 rounded-lg border px-2 text-sm" /><input aria-label={`${section} end date`} value={record.endDate ?? ""} onChange={(event) => setProfile((current) => updateAcceptedRecord(current, section, record.id, { endDate: event.target.value }))} placeholder="End date" className="min-h-9 rounded-lg border px-2 text-sm" /></> : null}<textarea aria-label={`${section} description`} value={record.description ?? ""} onChange={(event) => setProfile((current) => updateAcceptedRecord(current, section, record.id, { description: event.target.value }))} rows={2} className="rounded-lg border p-2 text-sm sm:col-span-2" /></div></article>;
}

function CareerProfilePreview({ profile, setProfile, audit, onClearGitHubData, onClearCareerProfile, onClearAll }: Props) {
  const preferences = profile.sectionPreferences;
  const toggle = (key: keyof typeof preferences) => setProfile({ ...profile, sectionPreferences: { ...preferences, [key]: !preferences[key] }, updatedAt: new Date().toISOString() });
  const headline = profile.careerDirection.professionalHeadline;
  const summary = profile.careerDirection.shortIntroduction;
  const linkValues = [profile.identity.website, profile.identity.linkedin, profile.identity.email].filter(Boolean);
  return <section aria-labelledby="career-profile-title"><p className="eyebrow">Step 5 · Career evidence profile</p><h2 id="career-profile-title" className="mt-3 text-3xl font-semibold tracking-[-.04em]">One profile, with sources preserved.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">This is structured evidence, not polished AI prose and not a prediction of career success.</p><div className="mt-5 flex flex-col gap-3 sm:flex-row"><Link to={`/career/${encodeURIComponent(profile.username)}/readme`} className="inline-flex justify-center rounded-xl bg-cobalt-600 px-5 py-3 text-sm font-semibold text-white">Build GitHub Profile README →</Link><Link to={`/career/${encodeURIComponent(profile.username)}/resume`} className="inline-flex justify-center rounded-xl bg-ink px-5 py-3 text-sm font-semibold text-white">Build LaTeX Resume →</Link></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-[.55fr_1fr]"><aside className="space-y-4"><Panel><p className="text-sm font-semibold">Profile completeness</p><div className="mt-4 space-y-3">{profile.derived.completeness.map((item) => <div key={item.key} className="flex items-start gap-3"><span className={item.complete ? "text-lime-700" : "text-amber-700"}>{item.complete ? "✓" : "⚠"}</span><div><p className="text-xs font-semibold">{item.label}</p><p className="text-[10px] leading-4 text-slate-500">{item.explanation}</p></div></div>)}</div></Panel><Panel><p className="text-sm font-semibold">Visible sections</p><div className="mt-3 space-y-2">{Object.entries(preferences).map(([key, enabled]) => <label key={key} className="flex items-center justify-between text-xs"><span>{key.replace(/([A-Z])/g, " $1")}</span><input type="checkbox" checked={enabled} onChange={() => toggle(key as keyof typeof preferences)} /></label>)}</div></Panel><Panel><p className="text-sm font-semibold">Data management</p><div className="mt-3 grid gap-2"><button type="button" onClick={() => setProfile((current) => clearResumeEvidence(current))} className="rounded-lg border px-3 py-2 text-left text-xs">Clear resume</button><button type="button" onClick={onClearGitHubData} className="rounded-lg border px-3 py-2 text-left text-xs">Clear GitHub data</button><button type="button" onClick={onClearCareerProfile} className="rounded-lg border px-3 py-2 text-left text-xs">Clear career profile</button><button type="button" onClick={onClearAll} className="rounded-lg border border-red-200 px-3 py-2 text-left text-xs text-red-700">Clear all career data</button></div></Panel></aside>
      <Panel><header className="border-b border-slate-200 pb-5"><div className="flex flex-wrap gap-2"><SourceBadge source={profile.identity.name?.provenance[0]?.source ?? "GITHUB_OBSERVED"} />{headline ? <SourceBadge source={headline.provenance[0]?.source ?? "USER_PROVIDED"} /> : null}</div><h3 className="mt-3 text-3xl font-semibold">{profile.identity.name?.value ?? audit.user.name ?? audit.user.login}</h3>{preferences.headline && headline ? <p className="mt-2 text-lg text-slate-600">{headline.value}</p> : null}{preferences.summary && summary ? <p className="mt-4 text-sm leading-6 text-slate-600">{summary.value}</p> : null}</header>
        {preferences.experience && profile.experience.length ? <div className="mt-6"><h4 className="text-lg font-semibold">Experience</h4><div className="mt-3 space-y-3">{profile.experience.map((record) => <RecordEditor key={record.id} record={record} section="experience" setProfile={setProfile} />)}</div></div> : null}
        {preferences.selectedProjects && profile.githubEvidence.repositories.length ? <div className="mt-6"><h4 className="text-lg font-semibold">Selected GitHub evidence</h4><div className="mt-3 grid gap-3 sm:grid-cols-2">{profile.githubEvidence.repositories.map((repository) => <article key={repository.repositoryId} className="rounded-xl border border-slate-200 p-4"><SourceBadge source="GITHUB_OBSERVED" /><Link to={`/audit/${encodeURIComponent(profile.username)}/repositories/${encodeURIComponent(profile.username)}/${encodeURIComponent(repository.name)}?from=career`} className="mt-2 block font-mono text-sm font-semibold text-cobalt-600 hover:underline">{repository.name}</Link><a href={repository.url} target="_blank" rel="noreferrer" className="mt-1 inline-flex text-[10px] text-slate-400 hover:underline">GitHub ↗</a><p className="mt-2 text-xs leading-5 text-slate-500">{repository.description ?? "Description not detected."}</p></article>)}</div></div> : null}
        {preferences.skills && profile.skills.length ? <div className="mt-6"><h4 className="text-lg font-semibold">Skills</h4><div className="mt-3 flex flex-wrap gap-2">{profile.skills.map((skill) => <span key={skill.id} className="rounded-lg border border-slate-200 px-3 py-2 text-xs"><strong>{skill.name}</strong> <span className="text-slate-400">· {skill.provenance.map((source) => source.source === "RESUME_PROVIDED" ? "Resume" : "You").join(" + ")}{skill.githubRepositoryIds.length ? " + GitHub" : ""}</span></span>)}</div></div> : null}
        {preferences.education && profile.education.length ? <div className="mt-6"><h4 className="text-lg font-semibold">Education</h4><div className="mt-3 space-y-3">{profile.education.map((record) => <RecordEditor key={record.id} record={record} section="education" setProfile={setProfile} />)}</div></div> : null}
        {preferences.certifications && profile.certifications.length ? <div className="mt-6"><h4 className="text-lg font-semibold">Certifications</h4><div className="mt-3 space-y-3">{profile.certifications.map((record) => <RecordEditor key={record.id} record={record} section="certifications" setProfile={setProfile} />)}</div></div> : null}
        {preferences.achievements && profile.achievements.length ? <div className="mt-6"><h4 className="text-lg font-semibold">Achievements</h4><div className="mt-3 space-y-3">{profile.achievements.map((record) => <RecordEditor key={record.id} record={record} section="achievements" setProfile={setProfile} />)}</div></div> : null}
        {preferences.links && linkValues.length ? <div className="mt-6"><h4 className="text-lg font-semibold">Links</h4><div className="mt-3 space-y-2">{linkValues.map((value) => <p key={value!.id} className="break-all text-sm text-cobalt-600">{Array.isArray(value!.value) ? value!.value.join(", ") : value!.value}</p>)}</div></div> : null}
      </Panel></div>
  </section>;
}

export function CareerProfileWorkspace(props: Props) {
  const [params, setParams] = useSearchParams();
  const requested = params.get("step");
  const initialStep: Step = requested === "resume" || requested === "review" || requested === "profile" || requested === "compare" || requested === "preview" ? requested : props.profile.resumeEvidence ? "review" : "resume";
  const [step, setStepState] = useState<Step>(initialStep);
  const setStep = (value: Step) => { setStepState(value); const next = new URLSearchParams(params); if (value === "preview") next.set("step", value); else next.delete("step"); setParams(next, { replace: true }); };
  const nav: Array<[Step, string]> = [["resume", "Resume"], ["review", "Review"], ["profile", "Profile"], ["compare", "Compare"], ["preview", "Evidence profile"]];
  return <div className="container-page pb-24 pt-8"><header className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-soft sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.15em] text-cobalt-600">Career evidence profile</p><h1 className="mt-1 text-2xl font-semibold tracking-[-.03em]">@{props.profile.username}</h1></div><div className="flex flex-col gap-2 sm:items-end"><p className={`text-xs ${props.saved ? "text-lime-700" : "text-amber-700"}`}>{props.saved ? "✓ Saved locally" : "Local save unavailable"}</p><div className="flex flex-wrap gap-2"><Link to={`/audit/${encodeURIComponent(props.profile.username)}/prepare`} className="rounded-lg border px-3 py-2 text-[10px] font-semibold">← GitHub preparation</Link><Link to={`/audit/${encodeURIComponent(props.profile.username)}`} className="rounded-lg border px-3 py-2 text-[10px] font-semibold">GitHub audit</Link></div></div></div><nav className="mt-6 grid grid-cols-5 gap-1 rounded-xl bg-slate-100 p-1" aria-label="Career profile steps">{nav.map(([value, label], index) => <button key={value} type="button" onClick={() => setStep(value)} aria-current={step === value ? "step" : undefined} className={`min-h-11 rounded-lg px-1 py-2 text-[10px] font-semibold sm:text-xs ${step === value ? "bg-white text-ink shadow-sm" : "text-slate-500"}`}><span className="hidden lg:inline">{index + 1}. </span>{label}</button>)}</nav></header>
    <main className="mt-10">{step === "resume" ? <ResumeInput profile={props.profile} setProfile={props.setProfile} goNext={() => setStep("review")} /> : step === "review" ? <ResumeReview profile={props.profile} setProfile={props.setProfile} goNext={() => setStep("profile")} /> : step === "profile" ? <UserProfileForm profile={props.profile} setProfile={props.setProfile} goNext={() => setStep("compare")} /> : step === "compare" ? <ComparisonView profile={props.profile} goNext={() => setStep("preview")} /> : <CareerProfilePreview {...props} />}</main>
  </div>;
}
