import { useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import type { CareerEvidenceProfile } from "../domain/career-evidence-profile";
import { loadCareerProfile } from "../features/career-profile/career-profile-storage";
import { LINKEDIN_SECTIONS, LINKEDIN_TEXT_LIMIT, emptyLinkedInSections, formatLinkedInReview, reviewLinkedInSections, type LinkedInReviewReport } from "../features/linkedin-review/linkedin-sections";
import { parseLinkedInProfileUrl } from "../features/linkedin-review/linkedin-profile-url";
import { downloadTextFile } from "../lib/browser-output";
import { ShieldIcon, TargetIcon } from "../components/icons";

function LinkedInReviewWorkspace({ profile }: { profile: CareerEvidenceProfile }) {
  const [mode, setMode] = useState<"paste" | "sections">("paste");
  const [pastedText, setPastedText] = useState("");
  const [sections, setSections] = useState(emptyLinkedInSections);
  const [active, setActive] = useState(0);
  const [report, setReport] = useState<LinkedInReviewReport | null>(null);
  const [profileInput, setProfileInput] = useState(profile.identity.linkedin?.value ?? "");
  const [profileError, setProfileError] = useState("");
  const [profileLink, setProfileLink] = useState("");
  const [message, setMessage] = useState("");
  const resultHeading = useRef<HTMLHeadingElement>(null);
  const section = LINKEDIN_SECTIONS[active]!;
  const total = Object.values(sections).reduce((sum, text) => sum + text.length, 0);
  const filled = Object.values(sections).filter((text) => text.trim()).length;
  function invalidate() { setReport(null); setMessage(""); }
  function review() {
    setReport(reviewLinkedInSections(profile, mode === "paste" ? pastedText : sections));
    setMessage("");
    requestAnimationFrame(() => resultHeading.current?.focus());
  }
  function clear() { setPastedText(""); setSections(emptyLinkedInSections()); setProfileInput(""); setProfileLink(""); setProfileError(""); invalidate(); }
  function download() {
    if (!report) return;
    try { downloadTextFile(formatLinkedInReview(report, profile.username), `${profile.username}-linkedin-review.txt`, "text/plain;charset=utf-8"); setMessage("Review download started. It includes findings and guidance, not your full pasted profile. Keep it private."); }
    catch { setMessage("The review could not be downloaded. Try again."); }
  }
  return <div className="container-page max-w-6xl pb-20 pt-8 sm:pt-12">
    <header className="rounded-[28px] bg-cobalt-950 p-6 text-white sm:p-8"><p className="font-mono text-[10px] font-semibold uppercase tracking-[.18em] text-lime-300">Your professional presence</p><h1 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Review your LinkedIn profile</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-cobalt-100">Bring your profile text. Review each section against your saved career evidence, then take a clear action plan back to LinkedIn.</p><p className="mt-3 flex items-center gap-2 text-xs leading-5 text-cobalt-100"><ShieldIcon className="h-4 w-4 shrink-0" />Pasted review text stays in this tab. It is not saved, sent to LinkedIn, or included in profile backups.</p></header>
    <section aria-labelledby="profile-source-title" className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 id="profile-source-title" className="text-lg font-semibold">1. Open your profile <span className="text-xs font-normal text-slate-600">Optional</span></h2><p className="mt-2 text-sm leading-6 text-slate-600">Use your LinkedIn username or public profile URL to open the right page, then copy the text you want to review. Your LinkedIn username may differ from your GitHub username.</p>
      <form className="mt-4" onSubmit={(event) => { event.preventDefault(); const parsed = parseLinkedInProfileUrl(profileInput); setProfileError(parsed.ok ? "" : parsed.message); setProfileLink(parsed.ok ? parsed.url : ""); }}>
        <label htmlFor="linkedin-username" className="text-sm font-semibold">LinkedIn username or profile URL</label><div className="mt-2 flex flex-col gap-2 sm:flex-row"><input id="linkedin-username" value={profileInput} onChange={(event) => { setProfileInput(event.target.value); setProfileLink(""); setProfileError(""); }} maxLength={500} spellCheck={false} placeholder="your-name or https://www.linkedin.com/in/your-name" aria-describedby="linkedin-source-help linkedin-source-error" aria-invalid={Boolean(profileError)} className="min-h-11 min-w-0 flex-1 rounded-xl border border-slate-300 px-3 text-sm" /><button type="submit" className="min-h-11 rounded-xl border border-slate-300 px-4 text-sm font-semibold">Prepare profile link</button></div>
      </form><p id="linkedin-source-error" role="alert" className="mt-2 text-sm text-red-700">{profileError}</p>{profileLink ? <a href={profileLink} target="_blank" rel="noreferrer" className="mt-2 inline-flex min-h-11 items-center text-sm font-semibold text-cobalt-700 underline">Open profile on LinkedIn ↗</a> : null}<p id="linkedin-source-help" className="mt-2 text-xs leading-5 text-slate-600">Opening a profile connects to LinkedIn and may require sign-in. This does not import its contents. Automatic reading by username is not connected.</p>
    </section>
    <section aria-labelledby="review-input-title" className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 id="review-input-title" className="text-lg font-semibold">2. Add what you want reviewed</h2><div role="group" aria-label="Review input mode" className="flex rounded-xl border border-slate-200 bg-white p-1">{([ ["paste", "Quick paste"], ["sections", "Guided sections"] ] as const).map(([value, label]) => <button key={value} type="button" aria-pressed={mode === value} onClick={() => { setMode(value); invalidate(); }} className={`min-h-11 rounded-lg px-4 text-xs font-semibold ${mode === value ? "bg-ink text-white" : "text-slate-600"}`}>{label}</button>)}</div></div>
      {mode === "paste" ? <div className="mt-4 rounded-2xl border bg-white p-5"><label className="block text-sm font-semibold" htmlFor="linkedin-profile-text">Your LinkedIn profile text</label><p id="linkedin-paste-help" className="mt-2 text-xs leading-5 text-slate-600">Paste visible text from your own profile. Keep headings such as About, Experience, Education, and Skills on separate lines. Unlabelled text is compared as a whole; use Guided sections for precise placement.</p><textarea id="linkedin-profile-text" value={pastedText} onChange={(event) => { setPastedText(event.target.value); invalidate(); }} maxLength={LINKEDIN_TEXT_LIMIT} rows={8} className="mt-3 w-full rounded-xl border border-slate-300 p-4 text-sm" placeholder={"Headline\nYour role and focus\n\nAbout\nYour introduction…"} aria-describedby="linkedin-paste-help linkedin-text-limit" /><p id="linkedin-text-limit" className="mt-1 text-xs text-slate-600">{pastedText.length.toLocaleString()} / 30,000 characters</p></div> : <div className="mt-4 grid overflow-hidden rounded-2xl border border-slate-200 bg-white md:grid-cols-[220px_1fr]">
        <nav aria-label="LinkedIn sections" className="border-b bg-slate-50 p-3 md:border-b-0 md:border-r"><p className="px-2 py-2 text-xs text-slate-600">{filled} of {LINKEDIN_SECTIONS.length} sections supplied</p><label htmlFor="linkedin-section-picker" className="sr-only">Choose a LinkedIn section</label><select id="linkedin-section-picker" value={active} onChange={(event) => setActive(Number(event.target.value))} className="min-h-11 w-full rounded-lg border bg-white px-2 text-sm md:hidden">{LINKEDIN_SECTIONS.map((item, index) => <option key={item.key} value={index}>{index + 1}. {item.short}{sections[item.key].trim() ? " · supplied" : ""}</option>)}</select><div className="hidden space-y-1 md:block">{LINKEDIN_SECTIONS.map((item, index) => <button key={item.key} type="button" aria-current={active === index ? "step" : undefined} onClick={() => setActive(index)} className={`flex min-h-11 w-full items-center justify-between gap-2 rounded-lg px-3 text-left text-xs font-semibold ${active === index ? "bg-cobalt-950 text-white" : "text-slate-600 hover:bg-white"}`}>{index + 1}. {item.short}{sections[item.key].trim() ? <span aria-label="Text supplied">✓</span> : null}</button>)}</div></nav>
        <div className="min-w-0 p-5 sm:p-6"><p className="text-xs font-semibold text-cobalt-700">Section {active + 1} of {LINKEDIN_SECTIONS.length}</p><label htmlFor="linkedin-section-text" className="mt-3 block text-xl font-semibold">{section.title}</label><p id="linkedin-section-help" className="mt-2 text-sm leading-6 text-slate-600">{section.hint}</p><textarea id="linkedin-section-text" value={sections[section.key]} onChange={(event) => { setSections({ ...sections, [section.key]: event.target.value }); invalidate(); }} maxLength={LINKEDIN_TEXT_LIMIT - total + sections[section.key].length} rows={8} aria-describedby="linkedin-section-help linkedin-section-limit" className="mt-4 w-full rounded-xl border border-slate-300 p-3 text-sm" placeholder={`Paste your ${section.short.toLowerCase()} text, or leave this section blank.`} /><p id="linkedin-section-limit" className="mt-1 text-xs leading-5 text-slate-600">{total.toLocaleString()} / 30,000 characters across sections. Blank sections remain unknown; they do not count against you.</p><div className="mt-4 flex justify-between gap-3"><button type="button" disabled={active === 0} onClick={() => setActive(active - 1)} className="min-h-11 rounded-lg border px-4 text-xs font-semibold disabled:opacity-50">Previous section</button><button type="button" disabled={active === LINKEDIN_SECTIONS.length - 1} onClick={() => setActive(active + 1)} className="min-h-11 rounded-lg border px-4 text-xs font-semibold disabled:opacity-50">Next section →</button></div></div>
      </div>}
      <div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" disabled={mode === "paste" ? !pastedText.trim() : !filled} onClick={review} className="min-h-11 rounded-xl bg-cobalt-600 px-5 py-2 text-sm font-semibold text-white disabled:bg-slate-500">Compare profiles</button><button type="button" onClick={clear} className="min-h-11 rounded-xl border border-slate-300 px-5 py-2 text-sm font-semibold">Clear pasted text</button><Link to={`/career/${encodeURIComponent(profile.username)}?step=preview`} className="inline-flex min-h-11 items-center px-2 text-sm font-semibold text-cobalt-700 underline">Back to career profile</Link></div>
    </section>
    {report ? <section className="mt-10" aria-labelledby="linkedin-results-title"><div className="flex flex-wrap items-center justify-between gap-3"><h2 ref={resultHeading} tabIndex={-1} id="linkedin-results-title" className="text-2xl font-semibold">Review results</h2><button type="button" onClick={download} className="min-h-11 rounded-xl border border-slate-300 bg-white px-4 text-sm font-semibold">Download review (.txt)</button></div><p className="mt-3 text-sm leading-6 text-slate-600">{report.supplied} of {LINKEDIN_SECTIONS.length} sections {mode === "paste" ? "identified in your paste" : "supplied"}. This describes your input, not profile quality. Unprovided sections may still exist on LinkedIn.</p><p className="mt-2 text-xs leading-5 text-slate-600">Phrase matches are wording clues, not verified claims. Paraphrases can be missed. Suggestions use simple text checks and your saved evidence; there is no hiring, visibility, or engagement score.</p><p role="status" className="mt-2 text-sm text-cobalt-700">{message}</p>
      <div className="mt-5 space-y-3">{report.sections.map((item) => <details key={item.key} open={item.supplied} className="rounded-2xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer text-sm font-semibold"><span>{item.title}</span><span className={`ml-3 inline-block rounded-full px-2 py-1 text-[10px] ${item.supplied ? "bg-cobalt-50 text-cobalt-700" : "bg-slate-100 text-slate-600"}`}>{item.supplied ? "Text supplied" : mode === "paste" ? "Not identified in paste" : "Not supplied"}</span></summary><div className="mt-4 space-y-4">{item.observations.length ? <ul className="list-disc space-y-2 pl-5 text-xs leading-6 text-slate-700">{item.observations.map((text) => <li key={text}>{text}</li>)}</ul> : <p className="text-xs leading-6 text-slate-600">Add this section when you want it reviewed. Its absence here is not a negative finding.</p>}{item.matches.length ? <ul className="space-y-2">{item.matches.map((match) => <li key={`${match.kind}:${match.label}`} className="break-words rounded-lg bg-slate-50 p-3 text-xs"><strong>{match.label}</strong><p className="mt-1 text-slate-600">{match.found ? "Phrase found" : "Exact phrase not found — review wording or evidence"}</p></li>)}</ul> : null}{item.reference.length ? <div><h3 className="text-xs font-semibold">Saved reference · check details manually</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-xs leading-6 text-slate-600">{item.reference.map((text, index) => <li key={index}>{text}</li>)}</ul></div> : null}<div><h3 className="flex items-center gap-2 text-xs font-semibold"><TargetIcon className="h-4 w-4 text-cobalt-700" />Suggested actions</h3><ul className="mt-2 list-disc space-y-2 pl-5 text-xs leading-6 text-slate-600">{item.prompts.map((text) => <li key={text}>{text}</li>)}</ul></div></div></details>)}</div>
      {mode === "paste" ? <details open className="mt-5 rounded-2xl border bg-white p-5"><summary className="cursor-pointer text-sm font-semibold">Whole-paste phrase comparison</summary><p className="mt-3 text-xs leading-6 text-slate-600">{report.phrases.filter((item) => item.found).length} of {report.phrases.length} career evidence phrases found somewhere in your paste. These matches are not assigned to a specific section.</p><ul className="mt-3 grid gap-3 sm:grid-cols-2">{report.phrases.map((item) => <li key={`${item.kind}:${item.label}`} className="min-w-0 rounded-lg bg-slate-50 p-3 text-xs"><span className="text-slate-600">{item.kind}</span><p className="mt-1 break-words font-semibold">{item.label}</p><p className="mt-2 text-slate-700">{item.found ? "Phrase found" : "Exact phrase not found — review wording or evidence"}</p></li>)}</ul></details> : null}
    </section> : null}
    <aside className="mt-8 border-t border-slate-200 pt-5 text-xs leading-6 text-slate-600"><p>Photos and banners need visual review. Endorsements and recommendations require human judgment. Posts are optional, and their performance cannot be assessed here.</p><p className="mt-2">Learn more: <a className="font-semibold text-cobalt-700 underline" href="https://www.linkedin.com/help/linkedin/answer/a546603/editing-your-profile?lang=en" target="_blank" rel="noreferrer">LinkedIn profile sections</a> · <a className="font-semibold text-cobalt-700 underline" href="https://www.linkedin.com/help/linkedin/answer/a565106?lang=en-US" target="_blank" rel="noreferrer">Skills and endorsements</a> · <a className="font-semibold text-cobalt-700 underline" href="https://learn.microsoft.com/en-us/linkedin/shared/integrations/people/profile-api" target="_blank" rel="noreferrer">Profile API access</a></p></aside>
  </div>;
}

export function LinkedInReviewPage() {
  const { username = "" } = useParams();
  const profile = loadCareerProfile(username);
  if (!profile) return <div className="container-page py-20"><h1 className="text-3xl font-semibold">Create a career profile first.</h1><Link to="/audit" className="mt-5 inline-block text-cobalt-700 underline">Start with GitHub audit</Link></div>;
  return <LinkedInReviewWorkspace key={profile.username} profile={profile} />;
}
