import { useState } from "react";
import { Link } from "react-router-dom";
import type { CareerEvidenceProfile } from "../domain/career-evidence-profile";
const stages = [
  { id: "graduate", label: "Fresher / graduate", focus: "Show what you can build and explain.", bring: "Coursework, personal or team projects, internships, education, and skills you have used. Employment experience is optional.", example: "For a team project, explain the problem, the part you built, the tools you used, and what someone can inspect." },
  { id: "mid", label: "Mid-level engineer", focus: "Make your ownership and results clear.", bring: "Roles, responsibilities, shipped work, relevant projects, and outcomes you can support. Add context that a repository cannot show.", example: "For a service you improved, describe your contribution, the constraint or decision, and the observed result. Use numbers only when you have them." },
  { id: "experienced", label: "Experienced engineer", focus: "Explain your scope, decisions, and impact.", bring: "System or team scope, architecture decisions, reliability or delivery improvements, mentoring, and leadership examples. Public code is optional evidence.", example: "Describe a technical decision, its trade-off, your responsibility, and the outcome. Summarize private work without sharing confidential details." },
] as const;
const goals = [
  { id: "resume", label: "A resume I can share", output: "An editable Word resume, with optional LaTeX source.", inputs: "Your career details and selected projects. Import a Word resume or enter details manually, then check and accept the evidence you want included.", finish: "Open the downloaded Word file, check names, dates, claims, links, and layout, then export it to PDF in your document editor if needed.", steps: ["Review your facts", "Choose resume content", "Download and check the file"] },
  { id: "readme", label: "A clearer GitHub profile", output: "A Markdown README explaining your focus and selected projects.", inputs: "A few relevant repositories, your contribution, and the introduction and links you want to share. A resume is optional.", finish: "Review the Markdown preview, download the README, and add it to your GitHub profile yourself. DevPersonify does not publish it.", steps: ["Choose representative projects", "Write your introduction", "Download and publish the README"] },
  { id: "linkedin", label: "A LinkedIn action plan", output: "Section-by-section review prompts and a downloadable text report.", inputs: "Your LinkedIn profile PDF or pasted sections, plus your saved career profile for wording comparisons.", finish: "Review each suggestion, decide which changes are accurate and useful, then make those changes on LinkedIn yourself.", steps: ["Import your LinkedIn text", "Check sections and suggestions", "Apply useful changes yourself"] },
] as const;
export function CareerOutcomeGuide({ profile, username }: { profile?: CareerEvidenceProfile | null; username?: string }) {
  const [goalId, setGoalId] = useState<typeof goals[number]["id"]>("resume");
  const [stageId, setStageId] = useState<typeof stages[number]["id"] | null>(null);
  const goal = goals.find((item) => item.id === goalId)!;
  const stage = stages.find((item) => item.id === stageId);
  const career = `/career/${encodeURIComponent(profile?.username ?? username ?? "")}`;
  const pending = profile?.resumeReview.some((item) => item.status === "PENDING");
  const destination = !profile ? username ? career : "/audit" : goalId === "resume" ? pending ? `${career}?step=review` : `${career}/resume` : `${career}/${goalId === "linkedin" ? "linkedin-review" : "readme"}`;
  const action = !profile ? username ? "Create your career profile" : "Start with your GitHub username" : goalId === "resume" ? pending ? "Review details for your resume" : "Choose your resume content" : goalId === "readme" ? "Choose your README content" : "Add your LinkedIn profile";
  return <section aria-labelledby="career-outcome-title" className="my-8 rounded-3xl border border-cobalt-100 bg-white p-5 sm:p-7">
    <p className="text-xs font-semibold uppercase tracking-wide text-cobalt-700">Choose your finish line</p>
    <h2 id="career-outcome-title" className="mt-2 text-2xl font-semibold tracking-tight">What do you want to leave with?</h2>
    <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Choose one useful output. You can stop when it is ready; you do not need to complete every tool or improve every repository score.</p>
    <div role="group" aria-label="Choose your outcome" className="mt-5 grid gap-2 sm:grid-cols-3">{goals.map((item) => <button type="button" key={item.id} aria-pressed={goalId === item.id} onClick={() => setGoalId(item.id)} className={`min-h-12 rounded-xl border px-4 py-3 text-left text-sm font-semibold ${goalId === item.id ? "border-cobalt-950 bg-cobalt-950 text-white" : "border-slate-200 bg-slate-50 text-slate-700"}`}>{item.label}</button>)}</div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h3 className="text-sm font-semibold">Your deliverable</h3><p className="mt-2 text-sm leading-6 text-slate-700">{goal.output}</p><h3 className="mt-4 text-sm font-semibold">What you bring</h3><p className="mt-2 text-sm leading-6 text-slate-600">{goal.inputs}</p></div><div className="rounded-xl bg-lime-50 p-4"><h3 className="text-sm font-semibold">You are done when…</h3><p className="mt-2 text-sm leading-6 text-slate-700">{goal.finish}</p></div></div>
    <ol className="mt-5 grid gap-2 sm:grid-cols-3">{goal.steps.map((step, index) => <li key={step} className="rounded-lg bg-slate-50 px-3 py-3 text-xs leading-5"><span className="mr-2 font-bold text-cobalt-700">{index + 1}.</span>{step}</li>)}</ol>
    <details className="mt-5 border-t pt-4"><summary className="cursor-pointer text-sm font-semibold">What should I focus on at my career stage?</summary><div role="group" aria-label="Your career stage" className="mt-3 flex flex-wrap gap-2">{stages.map((item) => <button type="button" key={item.id} aria-pressed={stageId === item.id} onClick={() => setStageId(item.id)} className={`min-h-11 rounded-lg border px-3 text-xs font-semibold ${stageId === item.id ? "bg-ink text-white" : "bg-white text-slate-700"}`}>{item.label}</button>)}</div>{stage ? <div className="mt-3 text-sm leading-6 text-slate-600"><h3 className="font-semibold text-ink">{stage.focus}</h3><p className="mt-2">{stage.bring}</p><p className="mt-2"><strong>Example to prepare:</strong> {stage.example}</p></div> : <p className="mt-3 text-xs leading-5 text-slate-600">Choose a stage for examples. This changes guidance only; it does not score or classify you.</p>}</details>
    {!profile ? <p className="mt-4 text-xs leading-6 text-slate-600">Current starting requirement: a GitHub username{username ? " (already supplied)" : ""}. After creating your career profile, you can add private-work summaries manually. Starting with a resume alone is not available yet.</p> : null}
    <Link to={destination} className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-cobalt-600 px-4 py-3 text-sm font-semibold text-white">{action} →</Link>
    <p className="mt-3 text-xs leading-5 text-slate-600">The app organizes your information, formats drafts, and flags wording to review. You verify the facts. It cannot assess private work, certify skills, or predict hiring outcomes.</p>
  </section>;
}
