import { useState } from "react";
import { Link } from "react-router-dom";
import type { CareerEvidenceProfile } from "../../domain/career-evidence-profile";
import type { GithubReadmeConfiguration, GithubReadmePresentation, GithubReadmeSections } from "../../domain/github-readme";
import { ShieldIcon } from "../../components/icons";
import { copyTextExactly, downloadTextFile } from "../../lib/browser-output";
import { SafeMarkdownPreview } from "../github-preparation/safe-markdown";
import { generateCareerGithubReadme } from "./career-readme-generator";
import { moveReadmeProject, setReadmePresentation, setReadmeProjectSelected, setReadmeSection } from "./readme-configuration";

interface Props {
  profile: CareerEvidenceProfile;
  config: GithubReadmeConfiguration;
  setConfig: (config: GithubReadmeConfiguration | ((current: GithubReadmeConfiguration) => GithubReadmeConfiguration)) => void;
  saved: boolean;
  onClear: () => void;
}

const sectionLabels: Array<[keyof GithubReadmeSections, string]> = [["introduction", "Introduction"], ["whatIBuild", "What I build"], ["selectedProjects", "Selected projects"], ["technologies", "Technologies"], ["openSource", "Open source"], ["contact", "Contact / links"]];
const presentationFields: Array<[keyof GithubReadmePresentation, string, boolean]> = [["professionalHeadline", "Professional headline", false], ["shortIntroduction", "Short introduction", true], ["currentFocus", "Current focus / what I build", true], ["preferredTechnologies", "Preferred technologies", false], ["additionalSkills", "Additional skills", false], ["location", "Location", false], ["website", "Website", false], ["linkedinUrl", "LinkedIn URL", false], ["email", "Email", false]];

export function CareerReadmeBuilder({ profile, config, setConfig, saved, onClear }: Props) {
  const [tab, setTab] = useState<"preview" | "source">("preview");
  const [copyStatus, setCopyStatus] = useState<"idle" | "copied" | "failed">("idle");
  const [downloadStatus, setDownloadStatus] = useState<"idle" | "started" | "failed">("idle");
  const markdown = generateCareerGithubReadme(profile, config);
  const selected = config.projectOrder.filter((id) => config.selectedProjectIds.includes(id));
  async function copy() {
    try { await copyTextExactly(markdown); setCopyStatus("copied"); window.setTimeout(() => setCopyStatus("idle"), 1800); }
    catch { setCopyStatus("failed"); }
  }
  function download() {
    try {
      downloadTextFile(markdown, `${profile.username}-github-profile-readme.md`, "text/markdown;charset=utf-8");
      setDownloadStatus("started");
      window.setTimeout(() => setDownloadStatus("idle"), 1800);
    } catch { setDownloadStatus("failed"); }
  }
  return <div className="container-page pb-24 pt-8"><header className="rounded-[28px] border border-slate-200 bg-white p-5 shadow-soft sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.15em] text-cobalt-600">GitHub profile README</p><h1 className="mt-1 text-2xl font-semibold tracking-[-.03em]">Build a profile README from shared evidence.</h1></div><p className={`text-xs ${saved ? "text-lime-700" : "text-amber-700"}`}>{saved ? "✓ README configuration saved locally" : "Local save unavailable"}</p></div></header>
    <div className="mt-6 flex gap-3 rounded-2xl border border-cobalt-100 bg-cobalt-50 p-4"><ShieldIcon className="h-5 w-5 shrink-0 text-cobalt-600" /><div><p className="text-sm font-semibold">Independent output configuration</p><p className="mt-1 text-xs leading-5 text-slate-600">README selections and presentation do not modify the Career Evidence Profile or LaTeX resume configuration.</p></div></div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[.72fr_1fr]"><aside className="space-y-5"><div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between gap-2"><h2 className="text-lg font-semibold">Repository selection</h2><span className="text-xs text-slate-600">{selected.length} selected</span></div><div className="mt-4 space-y-2">{profile.githubEvidence.repositories.map((repository) => { const isSelected = config.selectedProjectIds.includes(repository.repositoryId); const index = config.projectOrder.indexOf(repository.repositoryId); return <div key={repository.repositoryId} className="flex gap-2"><label className="flex min-w-0 flex-1 cursor-pointer items-start gap-3 rounded-xl border border-slate-100 p-3"><input type="checkbox" checked={isSelected} onChange={(event) => setConfig((current) => setReadmeProjectSelected(current, repository.repositoryId, event.target.checked))} className="mt-1" /><span className="min-w-0"><span className="flex flex-wrap items-center gap-2"><strong className="break-words font-mono text-xs">{repository.name}</strong><span className="rounded-md bg-lime-50 px-2 py-1 text-[9px] font-semibold text-lime-900">GitHub observed</span></span><span className="mt-1 line-clamp-2 block text-[10px] leading-4 text-slate-600">{repository.description ?? "Description not detected."}</span></span></label><Link aria-label={`Evidence details for ${repository.name}`} to={`/audit/${encodeURIComponent(profile.username)}/repositories/${encodeURIComponent(profile.username)}/${encodeURIComponent(repository.name)}?from=readme`} className="self-center rounded-md border px-2 py-2 text-[10px] font-semibold text-cobalt-600">Evidence</Link>{isSelected ? <div className="flex flex-col justify-center gap-1"><button type="button" aria-label={`Move ${repository.name} up`} disabled={index === 0} onClick={() => setConfig((current) => moveReadmeProject(current, repository.repositoryId, -1))} className="rounded-md border px-2 py-1 text-xs disabled:opacity-30">↑</button><button type="button" aria-label={`Move ${repository.name} down`} disabled={index === selected.length - 1} onClick={() => setConfig((current) => moveReadmeProject(current, repository.repositoryId, 1))} className="rounded-md border px-2 py-1 text-xs disabled:opacity-30">↓</button></div> : null}</div>; })}{!profile.githubEvidence.repositories.length ? <p className="rounded-xl border border-dashed p-4 text-xs text-slate-600">No selected GitHub evidence is available in the Career Evidence Profile.</p> : null}</div></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-semibold">README sections</h2><div className="mt-4 space-y-3">{sectionLabels.map(([key, label]) => <label key={key} className="flex items-center justify-between gap-3 text-sm"><span>{label}</span><input type="checkbox" checked={config.sections[key]} onChange={(event) => setConfig((current) => setReadmeSection(current, key, event.target.checked))} /></label>)}</div></div>
      <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between gap-2"><h2 className="text-lg font-semibold">README presentation</h2><span className="text-[10px] text-violet-600">Output-specific · You</span></div><div className="mt-4 space-y-4">{presentationFields.map(([key, label, multiline]) => <label key={key} className="block"><span className="text-xs font-semibold">{label}</span>{multiline ? <textarea rows={3} value={config.presentation[key]} onChange={(event) => setConfig((current) => setReadmePresentation(current, key, event.target.value))} className="mt-1 w-full rounded-xl border border-slate-300 p-3 text-sm" /> : <input value={config.presentation[key]} onChange={(event) => setConfig((current) => setReadmePresentation(current, key, event.target.value))} className="mt-1 min-h-10 w-full rounded-xl border border-slate-300 px-3 text-sm" />}</label>)}</div><button type="button" onClick={onClear} className="mt-5 text-xs font-semibold text-red-700">Clear README configuration</button></div></aside>
      <section className="min-w-0"><div className="sticky top-4 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-3"><div className="flex gap-1"><button type="button" onClick={() => setTab("preview")} aria-pressed={tab === "preview"} className={`rounded-lg px-3 py-2 text-xs font-semibold ${tab === "preview" ? "bg-ink text-white" : "text-slate-600"}`}>Preview</button><button type="button" onClick={() => setTab("source")} aria-pressed={tab === "source"} className={`rounded-lg px-3 py-2 text-xs font-semibold ${tab === "source" ? "bg-ink text-white" : "text-slate-600"}`}>Markdown source</button></div><div className="flex items-center gap-2"><button type="button" onClick={copy} className="rounded-lg border px-3 py-2 text-xs font-semibold">{copyStatus === "copied" ? "Copied" : copyStatus === "failed" ? "Copy failed" : "Copy"}</button><button type="button" onClick={download} className="rounded-lg bg-cobalt-600 px-3 py-2 text-xs font-semibold text-white">{downloadStatus === "started" ? "Download started" : downloadStatus === "failed" ? "Download failed" : "Download .md"}</button><span aria-live="polite" className="sr-only">{copyStatus === "copied" ? "Markdown copied to clipboard" : copyStatus === "failed" ? "Clipboard permission unavailable. Use the Markdown source tab to copy manually." : downloadStatus === "started" ? "Markdown download started" : downloadStatus === "failed" ? "Markdown download could not start" : ""}</span></div></div><div className="max-h-[78vh] overflow-auto p-5 sm:p-7">{tab === "preview" ? <SafeMarkdownPreview markdown={markdown} /> : <textarea readOnly aria-label="Generated career README Markdown source" value={markdown} className="min-h-[650px] w-full min-w-[580px] resize-none rounded-xl bg-slate-950 p-4 font-mono text-xs leading-6 text-slate-100 sm:min-w-0" />}</div></div></section></div>
  </div>;
}
